apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-framework-addon-dfsa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:71190b2729676cf58a777ec2bd4285f1cdb602eb328a9983148b91f5bb98cdab
        name: container-image
        resources: {}
status: {}
