apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-framework-addon-dfsa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ba93f20d13976cef65b6c0535a95041210c3d8af3500da52a2e49dfe83fe5fba
        name: container-image
        resources: {}
status: {}
