apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-framework-addon-dfsa
    app.kubernetes.io/part-of: governance-policy-framework-addon
  name: governance-policy-framework-addon-dfsa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-framework-addon/governance-policy-framework-addon-dfsa@sha256:f7c2fe697e924a749ac8f91609d670e214d890d9595c3b9eed37de31b43d7987
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
